#pragma once

#include "driver/gpio.h"

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_6

#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16

#define DISPLAY_SDA_PIN GPIO_NUM_41
#define DISPLAY_SCL_PIN GPIO_NUM_42
#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false

#define ML307_TX_PIN GPIO_NUM_12
#define ML307_RX_PIN GPIO_NUM_11
#define ML307_DTR_PIN GPIO_NUM_NC

#define SDCARD_CLK_PIN GPIO_NUM_13
#define SDCARD_CMD_PIN GPIO_NUM_14
#define SDCARD_D0_PIN GPIO_NUM_8
#define SDCARD_D1_PIN GPIO_NUM_9
#define SDCARD_D2_PIN GPIO_NUM_10
#define SDCARD_D3_PIN GPIO_NUM_17
#define SDCARD_MOUNT_POINT "/sdcard"
#define ENABLE_SDCARD_TEST 1
#define ENABLE_AUDIO_STORAGE_TEST 1
#define ENABLE_AUDIO_SELF_TEST 0
#define ENABLE_SONG_PLAYER_TEST 1
#define SONG_DEFAULT_PATH SDCARD_MOUNT_POINT "/music/SONG0001.WAV"

// Test firmware mode: PC sends 16 kHz / 20 ms / int16 PCM frames over UART0,
// ESP32 returns VAD decisions. Disable this to run the normal 4G app.
#define ENABLE_VAD_SERIAL_TEST 0
#define VAD_SERIAL_BAUD_RATE 921600
